kind: ConfigMap 
apiVersion: v1 
metadata:
  name: logstash-config
data:
  logstash.conf: |
    input {
       beats {
        port => 5044
      }
    }
    filter {
        if "json" in [tags] {
          json {
              source => "message"
          }
        }
        if "keyvalue" in [tags] {
          kv {
          }
        }
        if "appkeyvalue" in [tags] {
            grok {
                pattern_definitions => {
                  "CUS_PATH" => "\b\w+(/[[[:alnum:]]_%!$@:.,+~-]*)+"
                }
                match => [
                "message", "%{TIMESTAMP_ISO8601:timeStamp}\|%{LOGLEVEL:logLevel}\|(?:%{WORD:appName})\|P%{NUMBER:processId}\|T%{NUMBER:thread_id}\|%{CUS_PATH:fileName}\|%{WORD:funcName}\|L%{NUMBER:lineNum}\|(?:%{WORD:correlationId})?\|%{GREEDYDATA:msg}"
                ]
            }
            if [msg] {
              kv{
                source => "msg"
              }
            }
        }
    }
    output {
       elasticsearch {
          hosts => ["http://elasticsearch:9200"]
          ilm_rollover_alias => "custom"
          ilm_pattern => "%{[kubernetes][deployment][name]}-%{+yyyy.MM.dd.HH}-000001"
          ilm_policy => "custom_policy"
       }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
      name: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:7.16.2
        ports:
        - name: http
          containerPort: 5044
        args: [
          "-f", "/etc/logstash.conf",
        ]
        volumeMounts:
        - readOnly: true
          mountPath: /etc/logstash.conf
          subPath: logstash.conf
          name: logstash-config
      volumes:
      - name: logstash-config
        configMap:
          name: logstash-config
---
kind: Service
apiVersion: v1
metadata:
  name: logstash-service
  labels:
    app: logstash-service
spec:
  selector:
    app: logstash
  ports:
    - name: http
      protocol: TCP
      port: 5044
      targetPort: 5044
