kind: ConfigMap 
apiVersion: v1 
metadata:
  name: kibana-config
data:
  kibana.yml: |
    elasticsearch.username: kibana
    elasticsearch.password: iyVapXfsnYoponpMKUIs
    server.host: "0.0.0.0"
    server.shutdownTimeout: "5s"
    elasticsearch.hosts: [ "http://elasticsearch:9200" ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
      name: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.9.0
        ports:
        - name: http
          containerPort: 5601
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch:9200"
        volumeMounts:
        - readOnly: true
          mountPath: /usr/share/kibana/config/kibana.yml
          subPath: kibana.yml
          name: kibana-config
      volumes:
      - name: kibana-config
        configMap:
          name: kibana-config
---
kind: Service
apiVersion: v1
metadata:
  name: kibana-service
  labels:
    app: kibana-service
spec:
  selector:
    app: kibana
  ports:
    - name: http
      protocol: TCP
      port: 5601
      targetPort: 5601
