kind: ConfigMap 
apiVersion: v1 
metadata:
  name: logstash-config
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.enabled: true
    xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]
    xpack.monitoring.elasticsearch.username: logstash_system
    xpack.monitoring.elasticsearch.password: hxEWORZShE7J6dRqJLVz
  logstash.conf: |
    input {
       beats {
        port => 5044
      }
    }
    filter {
        if "json" in [tags] {
          json {
              source => "message"
          }
        }
        if "keyvalue" in [tags] {
          kv {
          }
        }
        if "appkeyvalue" in [tags] {
            grok {
                match => [
                "message", "%{TIMESTAMP_ISO8601:timeStamp}\|%{LOGLEVEL:logLevel}\|(?:%{DATA:appName})\|P%{NUMBER:processId}\|T%{NUMBER:thread_id}\|%{PATH:fileName}\|%{DATA:funcName}\|L%{NUMBER:lineNum}\|%{DATA:correlationId}\|%{GREEDYDATA:msg}"
                ]
            }
            if [msg] {
              kv{
                source => "msg"
              }
            }
        }
    }
    output {
       elasticsearch {
          hosts => ["http://elasticsearch:9200"]
          user => "elastic"
          password => "fJVauWdy3wnPLAQupv7d"
          doc_as_upsert => true
       }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  replicas: 3
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
      name:  logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.9.0
        ports:
        - name: http
          containerPort: 5044
        args: [
          "--log.level=debug","-f", "/etc/logstash.conf",
        ]
        volumeMounts:
        - readOnly: true
          mountPath: /etc/logstash.conf
          subPath: logstash.conf
          name: logstash-config
        - readOnly: true
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
          name: logstash-config
      volumes:
      - name: logstash-config
        configMap:
          name: logstash-config
---
kind: Service
apiVersion: v1
metadata:
  name: logstash-service
  labels:
    app: logstash-service
spec:
  selector:
    app: logstash
  ports:
    - name: http
      protocol: TCP
      port: 5044
      targetPort: 5044
