apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-vol-1
  labels:
    type: local
spec:
  #we use local node storage here!
  #kubectl get storageclass
  storageClassName: ""
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/home/kubeadmin/mnt/elk"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ptinawsldkubcpaas01
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-vol-2
  labels:
    type: local
spec:
  #we use local node storage here!
  #kubectl get storageclass
  storageClassName: ""
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/home/kubeadmin/mnt/elk"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ptinawsldkubcpaas02
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-vol-3
  labels:
    type: local
spec:
  #we use local node storage here!
  #kubectl get storageclass
  storageClassName: ""
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/home/kubeadmin/mnt/elk"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ptinawsldkubcpaas03
---